### PR TITLE
feat: Migrate the boilerplate to Vite #5

### PR DESCRIPTION
**Pull request by abdellatifAhammad**
feat: Migrate the existing boilerplate to Vite

This commit migrates the existing boilerplate to Vite, including:

- Configuration updates
- Dependency changes
- Necessary adjustments to make it compatible with Vite

I used [melonjs/typescript-boilerplate](https://github.com/melonjs/typescript-boilerplate) as a reference.

This addresses issue #5.

### CODE REVIEW

**Comment by obiot** [comment]
this is awesome, I've been meaning to do that but could not find the time ! give me 48 hours to merge and test it on my side :)

Thanks again !

**Comment by abdellatifAhammad** [comment]
hi Olivier , thanks a lot for melonjs game engine , it's really cool, and I am glad that my first PR would be on this project, ah BTW I didn't change the README file cause I didn't know how you would like it to be.

**Comment by obiot** [comment]
thank you for the feedback on melonJS, much appreciated ! once you get something you can share don't hesitate to share a link on discord or anywhere else :)

and np for the README, I will update it !

**Comment by obiot** [comment]
all done, I just pushed a commit with changes on the README and other things, do have a look and let me know if you see something I might have missed :)

thanks again so much for your contribution !

**Pull request merged**
